name: Prerelease

on:
  push:
      branches:
        - main
      tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build-test-publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Copy Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/settings.xml
          sed -i "s|<username>.*</username>|<username>${{github.actor}}</username>|" ~/.m2/settings.xml
          sed -i "s|<password>.*</password>|<password>${{ github.token }}</password>|" ~/.m2/settings.xml

      # --- Step 1: Build ---
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      # --- Step 2: Test ---
      - name: Run Tests
        env:
          MODEL_URL: https://example.com/api
        run: ./mvnw test

      # --- Step 3: Docker Build and Push ---
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "triggered_by=tag" >> $GITHUB_OUTPUT
          else
            echo "triggered_by=branch" >> $GITHUB_OUTPUT
          fi
        
      - name: Get latest tag from history
        if: steps.trigger.outputs.triggered_by == 'branch'
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get latest tag from pushed tag
        if: steps.trigger.outputs.triggered_by == 'tag'
        run: |
          LATEST_TAG=${GITHUB_REF:11}
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Calculate pre-release version
        run: |
          VERSION=${latest_tag#v}
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          if [[ "${{ steps.trigger.outputs.triggered_by }}" == "tag" ]]; then
            PATCH=$((PATCH + 1))
          fi
          DATETIME=$(date +%Y%m%d.%H%M%S)
          NEW_VERSION="$MAJOR.$MINOR.$PATCH-pre.$DATETIME"
          echo "version=$NEW_VERSION"  >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Tag pre-release commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          MAIN_SHA=$(git rev-parse origin/main)
          git tag v${{ env.version }} $MAIN_SHA
          git push origin v${{ env.version }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          prerelease: true

      - name: Build and Push Docker Image
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          IMG=${IMG@L}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG
